{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import sys\n",
        "import torch\n",
        "\n",
        "# Force torchao to be unimportable to prevent PEFT compatibility check crashes\n",
        "sys.modules[\"torchao\"] = None\n",
        "print(\"[INFO] Blocked torchao import via sys.modules mock to avoid PEFT package conflicts.\")\n",
        "\n",
        "use_unsloth = True\n",
        "if torch.cuda.is_available():\n",
        "    cap = torch.cuda.get_device_capability(0)\n",
        "    if cap[0] < 7:\n",
        "        print(f\"[INFO] GPU capability sm_{cap[0]}.{cap[1]} is less than sm_70. Skipping Unsloth installation to preserve Kaggle default PyTorch compatibility on P100!\")\n",
        "        use_unsloth = False\n",
        "\n",
        "def install_dependencies():\n",
        "    print(\"Installing Unsloth library on Kaggle GPU instance...\")\n",
        "    import subprocess\n",
        "    try:\n",
        "        subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"unsloth\", \"--quiet\"], check=True)\n",
        "        print(\"Unsloth installed successfully!\")\n",
        "    except Exception as e:\n",
        "        print(\"Error installing Unsloth:\", e)\n",
        "\n",
        "if use_unsloth:\n",
        "    try:\n",
        "        from unsloth import FastLanguageModel\n",
        "    except ImportError:\n",
        "        install_dependencies()\n",
        "import os\n",
        "import re\n",
        "import sys\n",
        "import random\n",
        "import json\n",
        "import math\n",
        "import html\n",
        "import time\n",
        "import gc\n",
        "import logging\n",
        "import traceback\n",
        "import ast\n",
        "import signal\n",
        "import urllib.parse\n",
        "import hashlib\n",
        "import concurrent.futures\n",
        "from dataclasses import dataclass\n",
        "from typing import List, Dict, Any, Tuple\n",
        "\n",
        "try:\n",
        "    import gradio as gr\n",
        "    _GRADIO_AVAILABLE = True\n",
        "except ImportError:\n",
        "    _GRADIO_AVAILABLE = False\n",
        "\n",
        "try:\n",
        "    from tqdm import tqdm\n",
        "except ImportError:\n",
        "    def tqdm(iterable, *args, **kwargs):\n",
        "        return iterable\n",
        "\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.nn.functional as F\n",
        "\n",
        "use_unsloth = True\n",
        "if torch.cuda.is_available():\n",
        "    cap = torch.cuda.get_device_capability(0)\n",
        "    if cap[0] < 7:\n",
        "        use_unsloth = False\n",
        "\n",
        "# Monkeypatch torch.Tensor.to to redirect to CPU if GPU fallback is active\n",
        "_orig_to = torch.Tensor.to\n",
        "def patched_to(self, *args, **kwargs):\n",
        "    if not use_unsloth:\n",
        "        if len(args) > 0:\n",
        "            if isinstance(args[0], str) and \"cuda\" in args[0]:\n",
        "                args = (\"cpu\",) + args[1:]\n",
        "            elif isinstance(args[0], torch.device) and args[0].type == \"cuda\":\n",
        "                args = (torch.device(\"cpu\"),) + args[1:]\n",
        "        if \"device\" in kwargs:\n",
        "            dev = kwargs[\"device\"]\n",
        "            if isinstance(dev, str) and \"cuda\" in dev:\n",
        "                kwargs[\"device\"] = \"cpu\"\n",
        "            elif isinstance(dev, torch.device) and dev.type == \"cuda\":\n",
        "                kwargs[\"device\"] = torch.device(\"cpu\")\n",
        "    return _orig_to(self, *args, **kwargs)\n",
        "torch.Tensor.to = patched_to\n",
        "\n",
        "if use_unsloth:\n",
        "    try:\n",
        "        from unsloth import FastLanguageModel, PatchFastRL\n",
        "    except ImportError:\n",
        "        use_unsloth = False\n",
        "\n",
        "if not use_unsloth:\n",
        "    class FastLanguageModel:\n",
        "        @classmethod\n",
        "        def for_inference(cls, model):\n",
        "            pass\n",
        "        @classmethod\n",
        "        def for_training(cls, model):\n",
        "            pass\n",
        "        @classmethod\n",
        "        def from_pretrained(cls, model_name, max_seq_length, load_in_4bit=True, fast_inference=False, trust_remote_code=True, device_map=\"cuda:0\"):\n",
        "            from transformers import AutoModelForCausalLM, AutoTokenizer\n",
        "            print(f\"[INFO] Disabling Unsloth and loading standard model on {device_map} (GPU Capability < 7.0 fallback)...\")\n",
        "            tokenizer = AutoTokenizer.from_pretrained(model_name)\n",
        "            tokenizer.pad_token_id = tokenizer.eos_token_id\n",
        "            \n",
        "            model = AutoModelForCausalLM.from_pretrained(\n",
        "                model_name,\n",
        "                torch_dtype=torch.float16,\n",
        "                trust_remote_code=trust_remote_code,\n",
        "                device_map=\"cpu\"\n",
        "            )\n",
        "            \n",
        "            import types\n",
        "            def save_pretrained_merged(self, save_directory, tokenizer, save_method=\"merged_16bit\"):\n",
        "                print(f\"[INFO] Merging and saving standard Hugging Face model to {save_directory}...\")\n",
        "                merged = self.merge_and_unload()\n",
        "                merged.save_pretrained(save_directory)\n",
        "                tokenizer.save_pretrained(save_directory)\n",
        "                \n",
        "            def save_pretrained_gguf(self, save_directory, tokenizer, quantization_method=\"f16\"):\n",
        "                print(f\"[WARNING] GGUF conversion is only supported with active Unsloth. Skipping GGUF conversion for quantization_method='{quantization_method}'.\")\n",
        "                \n",
        "            model.save_pretrained_merged = types.MethodType(save_pretrained_merged, model)\n",
        "            model.save_pretrained_gguf = types.MethodType(save_pretrained_gguf, model)\n",
        "            return model, tokenizer\n",
        "            \n",
        "        @classmethod\n",
        "        def get_peft_model(cls, model, r, target_modules, lora_alpha, use_gradient_checkpointing=True, random_state=42):\n",
        "            from peft import LoraConfig, get_peft_model\n",
        "            peft_config = LoraConfig(\n",
        "                r=r,\n",
        "                lora_alpha=lora_alpha,\n",
        "                target_modules=target_modules,\n",
        "                lora_dropout=0.05,\n",
        "                bias=\"none\",\n",
        "                task_type=\"CAUSAL_LM\"\n",
        "            )\n",
        "            return get_peft_model(model, peft_config)\n",
        "            \n",
        "    def PatchFastRL(*args, **kwargs): pass\n",
        "\n",
        "from collections import Counter\n",
        "from torch.optim import AdamW\n",
        "\n",
        "try:\n",
        "    from peft import get_peft_model_state_dict\n",
        "except ImportError:\n",
        "    def get_peft_model_state_dict(*args, **kwargs):\n",
        "        return {}\n",
        "\n",
        "try:\n",
        "    from transformers import StoppingCriteria, StoppingCriteriaList\n",
        "except ImportError:\n",
        "    class StoppingCriteria: pass\n",
        "    class StoppingCriteriaList(list):\n",
        "        def __init__(self, *args, **kwargs):\n",
        "            super().__init__(*args, **kwargs)\n",
        "\n",
        "# Structured logging configuration\n",
        "logging.basicConfig(\n",
        "    level=logging.INFO,\n",
        "    format=\"%(asctime)s [%(levelname)s] %(name)s: %(message)s\",\n",
        "    handlers=[logging.StreamHandler(sys.stdout)]\n",
        ")\n",
        "logger = logging.getLogger(\"AGI_Pipeline_V3\")\n",
        "\n",
        "@dataclass\n",
        "class TrainingConfig:\n",
        "    model_name: str = \"LiquidAI/LFM2.5-230M-Base\"\n",
        "    max_seq_length: int = 1024\n",
        "    max_new_tokens: int = 384     # Turn 1 generation token limit\n",
        "    max_new_tokens_turn2: int = 768 # Turn 2 critique + correction limit\n",
        "    lora_r: int = 16\n",
        "    lora_alpha: int = 32\n",
        "    learning_rate: float = 1e-5\n",
        "    weight_decay: float = 0.01\n",
        "    max_grad_norm: float = 1.0\n",
        "    gamma_margin: float = 0.5\n",
        "    lambda_symmetry: float = 0.5\n",
        "    beta: float = 2.0\n",
        "    accumulation_steps: int = 4\n",
        "    G_group_size: int = 4  # GRPO Group size\n",
        "    num_epochs: int = 15   # High-frequency off-policy replay buffer training epochs\n",
        "    kl_coeff: float = 0.02 # KL divergence penalty coefficient\n",
        "    train_split_ratio: float = 0.85\n",
        "    save_checkpoint_dir: str = \"./checkpoints\"\n",
        "    trust_remote_code: bool = True\n",
        "\n",
        "\n",
        "# Safe import of requests for active web searches\n",
        "try:\n",
        "    import requests\n",
        "    _REQUESTS_AVAILABLE = True\n",
        "except ImportError:\n",
        "    _REQUESTS_AVAILABLE = False\n",
        "    logger.warning(\"Package 'requests' is not installed. Web search queries will fail gracefully.\")\n",
        "\n",
        "# Enable Unsloth's optimized reinforcement learning kernels to save VRAM on the T4 GPU\n",
        "try:\n",
        "    PatchFastRL(\"GRPO\", FastLanguageModel)\n",
        "except Exception:\n",
        "    pass\n",
        "\n",
        "\n",
        "# ==============================================================================\n",
        "# Helper Functions for GRPO Policy Ratios & Model Merging\n",
        "# ==============================================================================\n",
        "\n",
        "def get_sequence_log_prob(model, tokenizer, prompt: str, completion: str) -> torch.Tensor:\n",
        "    \"\"\"\n",
        "    Computes the length-normalized log probability of the completion tokens conditioned on the prompt.\n",
        "    Retains gradients for backpropagation.\n",
        "    \"\"\"\n",
        "    prompt_tokens = tokenizer(prompt, return_tensors=\"pt\")\n",
        "    full_tokens = tokenizer(prompt + completion, return_tensors=\"pt\")\n",
        "    \n",
        "    prompt_len = prompt_tokens[\"input_ids\"].shape[1]\n",
        "    full_len = full_tokens[\"input_ids\"].shape[1]\n",
        "    \n",
        "    if full_len <= prompt_len:\n",
        "        return torch.tensor(0.0, device=model.device, requires_grad=True)\n",
        "        \n",
        "    input_ids = full_tokens[\"input_ids\"].to(model.device)\n",
        "    attention_mask = full_tokens[\"attention_mask\"].to(model.device)\n",
        "    \n",
        "    outputs = model(input_ids=input_ids, attention_mask=attention_mask)\n",
        "    logits = outputs.logits  # shape: (batch_size, sequence_length, vocab_size)\n",
        "    \n",
        "    # We want the log probs of the completion tokens\n",
        "    completion_logits = logits[0, prompt_len - 1 : full_len - 1, :]\n",
        "    completion_targets = input_ids[0, prompt_len : full_len]\n",
        "    \n",
        "    log_probs = F.log_softmax(completion_logits, dim=-1)\n",
        "    token_log_probs = log_probs.gather(dim=-1, index=completion_targets.unsqueeze(-1)).squeeze(-1)\n",
        "    \n",
        "    return token_log_probs.mean()\n",
        "\n",
        "\n",
        "def run_slerp_adapter_merge(model, weights_v0: Dict[str, torch.Tensor], weights_v1: Dict[str, torch.Tensor], t: float = 0.5) -> Dict[str, torch.Tensor]:\n",
        "    \"\"\"\n",
        "    Applies Spherical Linear Interpolation (SLERP) to merge two sets of LoRA adapter weights.\n",
        "    \"\"\"\n",
        "    merged_weights = {}\n",
        "    for key in weights_v0.keys():\n",
        "        if key not in weights_v1:\n",
        "            merged_weights[key] = weights_v0[key].clone()\n",
        "            continue\n",
        "            \n",
        "        v0 = weights_v0[key]\n",
        "        v1 = weights_v1[key]\n",
        "        \n",
        "        orig_shape = v0.shape\n",
        "        v0_flat = v0.view(-1).float()\n",
        "        v1_flat = v1.view(-1).float()\n",
        "        \n",
        "        v0_norm = torch.norm(v0_flat)\n",
        "        v1_norm = torch.norm(v1_flat)\n",
        "        \n",
        "        if v0_norm < 1e-8 or v1_norm < 1e-8:\n",
        "            merged_flat = (1 - t) * v0_flat + t * v1_flat\n",
        "        else:\n",
        "            v0_unit = v0_flat / v0_norm\n",
        "            v1_unit = v1_flat / v1_norm\n",
        "            \n",
        "            dot = torch.dot(v0_unit, v1_unit)\n",
        "            dot = torch.clamp(dot, -1.0, 1.0)\n",
        "            \n",
        "            omega = torch.acos(dot)\n",
        "            sin_omega = torch.sin(omega)\n",
        "            \n",
        "            if sin_omega < 1e-4:\n",
        "                merged_flat = (1 - t) * v0_flat + t * v1_flat\n",
        "            else:\n",
        "                weight_v0 = torch.sin((1 - t) * omega) / sin_omega\n",
        "                weight_v1 = torch.sin(t * omega) / sin_omega\n",
        "                merged_flat = weight_v0 * v0_flat + weight_v1 * v1_flat\n",
        "                \n",
        "                target_norm = (1 - t) * v0_norm + t * v1_norm\n",
        "                merged_flat = (merged_flat / torch.norm(merged_flat)) * target_norm\n",
        "                \n",
        "        merged_weights[key] = merged_flat.view(orig_shape).to(v0.dtype)\n",
        "        \n",
        "    return merged_weights\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# 1. AST LOOP-LIMITER (DETERMINISTIC VISITOR)\n",
        "# ==========================================\n",
        "\n",
        "class LoopLimiterTransformer(ast.NodeTransformer):\n",
        "    \"\"\"\n",
        "    Deterministic AST transformer that injects loop counter initializations\n",
        "    immediately before any For or While loop, and injects guard statements\n",
        "    at the start of the loop body.\n",
        "    \"\"\"\n",
        "    def __init__(self, limit: int = 5000):\n",
        "        super().__init__()\n",
        "        self.limit = limit\n",
        "        self.counter_id = 0\n",
        "\n",
        "    def _generate_counter_name(self) -> str:\n",
        "        name = f\"_loop_counter_{self.counter_id}\"\n",
        "        self.counter_id += 1\n",
        "        return name\n",
        "\n",
        "    def visit_For(self, node: ast.For) -> Any:\n",
        "        self.generic_visit(node)\n",
        "        counter_name = self._generate_counter_name()\n",
        "        \n",
        "        init_node = ast.Assign(\n",
        "            targets=[ast.Name(id=counter_name, ctx=ast.Store())],\n",
        "            value=ast.Constant(value=0)\n",
        "        )\n",
        "        increment = ast.AugAssign(\n",
        "            target=ast.Name(id=counter_name, ctx=ast.Store()),\n",
        "            op=ast.Add(),\n",
        "            value=ast.Constant(value=1)\n",
        "        )\n",
        "        check = ast.If(\n",
        "            test=ast.Compare(\n",
        "                left=ast.Name(id=counter_name, ctx=ast.Load()),\n",
        "                ops=[ast.Gt()],\n",
        "                comparators=[ast.Constant(value=self.limit)]\n",
        "            ),\n",
        "            body=[\n",
        "                ast.Raise(\n",
        "                    exc=ast.Call(\n",
        "                        func=ast.Name(id=\"TimeoutError\", ctx=ast.Load()),\n",
        "                        args=[ast.Constant(value=\"Loop threshold exceeded.\")],\n",
        "                        keywords=[]\n",
        "                    )\n",
        "                )\n",
        "            ],\n",
        "            orelse=[]\n",
        "        )\n",
        "        \n",
        "        node.body = [increment, check] + node.body\n",
        "        return [init_node, node]\n",
        "\n",
        "    def visit_While(self, node: ast.While) -> Any:\n",
        "        self.generic_visit(node)\n",
        "        counter_name = self._generate_counter_name()\n",
        "        \n",
        "        init_node = ast.Assign(\n",
        "            targets=[ast.Name(id=counter_name, ctx=ast.Store())],\n",
        "            value=ast.Constant(value=0)\n",
        "        )\n",
        "        increment = ast.AugAssign(\n",
        "            target=ast.Name(id=counter_name, ctx=ast.Store()),\n",
        "            op=ast.Add(),\n",
        "            value=ast.Constant(value=1)\n",
        "        )\n",
        "        check = ast.If(\n",
        "            test=ast.Compare(\n",
        "                left=ast.Name(id=counter_name, ctx=ast.Load()),\n",
        "                ops=[ast.Gt()],\n",
        "                comparators=[ast.Constant(value=self.limit)]\n",
        "            ),\n",
        "            body=[\n",
        "                ast.Raise(\n",
        "                    exc=ast.Call(\n",
        "                        func=ast.Name(id=\"TimeoutError\", ctx=ast.Load()),\n",
        "                        args=[ast.Constant(value=\"Loop threshold exceeded.\")],\n",
        "                        keywords=[]\n",
        "                    )\n",
        "                )\n",
        "            ],\n",
        "            orelse=[]\n",
        "        )\n",
        "        \n",
        "        node.body = [increment, check] + node.body\n",
        "        return [init_node, node]\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# 2. SECURE AST MATHEMATICAL PARSER\n",
        "# ==========================================\n",
        "\n",
        "def calculate_expression(expr: str) -> str:\n",
        "    \"\"\"\n",
        "    100% secure math parser using explicit AST node evaluation.\n",
        "    \"\"\"\n",
        "    allowed_operators = {\n",
        "        ast.Add: lambda x, y: x + y,\n",
        "        ast.Sub: lambda x, y: x - y,\n",
        "        ast.Mult: lambda x, y: x * y,\n",
        "        ast.Div: lambda x, y: x / y if y != 0 else float('nan'),\n",
        "        ast.Pow: lambda x, y: x ** y if y < 100 else float('inf'),\n",
        "        ast.USub: lambda x: -x,\n",
        "        ast.UAdd: lambda x: +x\n",
        "    }\n",
        "    allowed_constants = {\n",
        "        \"pi\": math.pi,\n",
        "        \"e\": math.e\n",
        "    }\n",
        "    \n",
        "    def _eval_node(node):\n",
        "        if isinstance(node, ast.Expression):\n",
        "            return _eval_node(node.body)\n",
        "        elif isinstance(node, ast.Constant):\n",
        "            if isinstance(node.value, (int, float)):\n",
        "                return float(node.value)\n",
        "            raise ValueError(\"Unsupported constant type.\")\n",
        "        elif isinstance(node, ast.Name):\n",
        "            if node.id in allowed_constants:\n",
        "                return allowed_constants[node.id]\n",
        "            raise ValueError(f\"Variables restricted: '{node.id}'\")\n",
        "        elif isinstance(node, ast.BinOp):\n",
        "            left_val = _eval_node(node.left)\n",
        "            right_val = _eval_node(node.right)\n",
        "            op_type = type(node.op)\n",
        "            if op_type in allowed_operators:\n",
        "                return allowed_operators[op_type](left_val, right_val)\n",
        "            raise TypeError(f\"Unsupported operator: {op_type}\")\n",
        "        elif isinstance(node, ast.UnaryOp):\n",
        "            operand_val = _eval_node(node.operand)\n",
        "            op_type = type(node.op)\n",
        "            if op_type in allowed_operators:\n",
        "                return allowed_operators[op_type](operand_val)\n",
        "            raise TypeError(f\"Unsupported operator: {op_type}\")\n",
        "        raise TypeError(f\"Unsupported expression construct: {type(node)}\")\n",
        "\n",
        "    cleaned = re.sub(r\"[^0-9\\+\\-\\*\\/\\(\\)\\.a-zA-Z_ ]\", \"\", expr)\n",
        "    try:\n",
        "        tree = ast.parse(cleaned, mode=\"eval\")\n",
        "        res = _eval_node(tree)\n",
        "        return str(res)\n",
        "    except Exception as e:\n",
        "        return f\"Error: Safe calculation parsing failed: {e}\"\n",
        "\n",
        "\n",
        "def binary_search_solver(target: float, low: float, high: float) -> str:\n",
        "    \"\"\"Pre-built optimized convergence algorithm for search agents.\"\"\"\n",
        "    l, h = float(low), float(high)\n",
        "    steps = 0\n",
        "    mid = l\n",
        "    while h - l > 1e-5 and steps < 100:\n",
        "        mid = (l + h) / 2\n",
        "        if mid < target:\n",
        "            l = mid\n",
        "        else:\n",
        "            h = mid\n",
        "        steps += 1\n",
        "    return f\"Target convergent mid-point calculated at {mid:.5f} after {steps} steps.\"\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# 3. REAL WEB SEARCH ADAPTER\n",
        "# ==========================================\n",
        "\n",
        "class RealSearchAdapter:\n",
        "    \"\"\"\n",
        "    Manages external web search transactions.\n",
        "    \"\"\"\n",
        "    def __init__(self, cache_file=\"search_cache.json\"):\n",
        "        self.cache_file = cache_file\n",
        "        self.cache = {}\n",
        "        self.last_request_time = 0.0\n",
        "        self.rate_limit_delay = 1.0\n",
        "        self.load_cache()\n",
        "\n",
        "    def load_cache(self):\n",
        "        if os.path.exists(self.cache_file):\n",
        "            try:\n",
        "                with open(self.cache_file, \"r\", encoding=\"utf-8\") as f:\n",
        "                    self.cache = json.load(f)\n",
        "                logger.info(f\"Loaded {len(self.cache)} records from search cache.\")\n",
        "            except Exception as e:\n",
        "                logger.error(f\"Failed to load search cache from disk: {e}\")\n",
        "\n",
        "    def save_cache(self):\n",
        "        try:\n",
        "            with open(self.cache_file, \"w\", encoding=\"utf-8\") as f:\n",
        "                json.dump(self.cache, f, ensure_ascii=False, indent=2)\n",
        "        except Exception as e:\n",
        "            logger.error(f\"Failed to write search cache to disk: {e}\")\n",
        "\n",
        "    def query(self, search_query: str) -> str:\n",
        "        search_query = search_query.strip()\n",
        "        if not search_query:\n",
        "            return \"Error: Empty query parameter received.\"\n",
        "\n",
        "        if search_query in self.cache:\n",
        "            logger.info(f\"Search Cache Hit: {search_query}\")\n",
        "            return self.cache[search_query]\n",
        "\n",
        "        if not _REQUESTS_AVAILABLE:\n",
        "            return f\"Error: Web search requested but requests package is not installed.\"\n",
        "\n",
        "        elapsed = time.time() - self.last_request_time\n",
        "        if elapsed < self.rate_limit_delay:\n",
        "            time.sleep(self.rate_limit_delay - elapsed)\n",
        "\n",
        "        tavily_key = os.environ.get(\"TAVILY_API_KEY\")\n",
        "        serper_key = os.environ.get(\"SERPER_API_KEY\")\n",
        "        result = None\n",
        "\n",
        "        if tavily_key:\n",
        "            result = self._search_tavily(search_query, tavily_key)\n",
        "        elif serper_key:\n",
        "            result = self._search_serper(search_query, serper_key)\n",
        "        \n",
        "        if not result:\n",
        "            result = self._search_ddg(search_query)\n",
        "\n",
        "        self.last_request_time = time.time()\n",
        "\n",
        "        if result:\n",
        "            self.cache[search_query] = result\n",
        "            self.save_cache()\n",
        "            return result\n",
        "\n",
        "        return f\"Search completed. No active matching records found online for query: '{search_query}'.\"\n",
        "\n",
        "    def _search_tavily(self, query: str, api_key: str) -> str:\n",
        "        headers = {\"Content-Type\": \"application/json\"}\n",
        "        payload = {\n",
        "            \"api_key\": api_key,\n",
        "            \"query\": query,\n",
        "            \"search_depth\": \"basic\",\n",
        "            \"max_results\": 3\n",
        "        }\n",
        "        for attempt in range(2):\n",
        "            try:\n",
        "                response = requests.post(\"https://api.tavily.com/search\", json=payload, headers=headers, timeout=5.0)\n",
        "                if response.status_code == 200:\n",
        "                    data = response.json()\n",
        "                    results = data.get(\"results\", [])\n",
        "                    snippets = [r.get(\"content\", \"\") for r in results if r.get(\"content\")]\n",
        "                    if snippets:\n",
        "                        return \" | \".join(snippets[:3])\n",
        "            except Exception as e:\n",
        "                logger.error(f\"Tavily search failed: {e}\")\n",
        "                time.sleep(1.0)\n",
        "        return None\n",
        "\n",
        "    def _search_serper(self, query: str, api_key: str) -> str:\n",
        "        headers = {\n",
        "            \"X-API-KEY\": api_key,\n",
        "            \"Content-Type\": \"application/json\"\n",
        "        }\n",
        "        payload = {\"q\": query, \"num\": 3}\n",
        "        for attempt in range(2):\n",
        "            try:\n",
        "                response = requests.post(\"https://google.serper.dev/search\", json=payload, headers=headers, timeout=5.0)\n",
        "                if response.status_code == 200:\n",
        "                    data = response.json()\n",
        "                    results = data.get(\"organic\", [])\n",
        "                    snippets = [r.get(\"snippet\", \"\") for r in results if r.get(\"snippet\")]\n",
        "                    if snippets:\n",
        "                        return \" | \".join(snippets[:3])\n",
        "            except Exception as e:\n",
        "                logger.error(f\"Serper search failed: {e}\")\n",
        "                time.sleep(1.0)\n",
        "        return None\n",
        "\n",
        "    def _search_ddg(self, query: str) -> str:\n",
        "        headers = {\n",
        "            \"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36\"\n",
        "        }\n",
        "        try:\n",
        "            url_api = f\"https://api.duckduckgo.com/?q={urllib.parse.quote(query)}&format=json&no_html=1\"\n",
        "            response = requests.get(url_api, headers=headers, timeout=5.0)\n",
        "            if response.status_code == 200:\n",
        "                data = response.json()\n",
        "                abstract = data.get(\"AbstractText\", \"\")\n",
        "                if abstract:\n",
        "                    return f\"Abstract: {abstract}\"\n",
        "                related = data.get(\"RelatedTopics\", [])\n",
        "                snippets = [r.get(\"Text\", \"\") for r in related if \"Text\" in r]\n",
        "                if snippets:\n",
        "                    return \" | \".join(snippets[:3])\n",
        "        except Exception as e:\n",
        "            logger.debug(f\"Direct DDG API call failed, falling back to layout-agnostic HTML scrape: {e}\")\n",
        "\n",
        "        url = \"https://html.duckduckgo.com/html/\"\n",
        "        data = {\"q\": query}\n",
        "        \n",
        "        for attempt in range(3):\n",
        "            try:\n",
        "                if attempt > 0:\n",
        "                    time.sleep(2.0 ** attempt)\n",
        "                response = requests.post(url, data=data, headers=headers, timeout=5.0)\n",
        "                if response.status_code == 200:\n",
        "                    html_content = response.text\n",
        "                    snippets = re.findall(r'<a class=\"result__snippet[^\"]*\"[^>]*>(.*?)</a>', html_content, re.DOTALL)\n",
        "                    if not snippets:\n",
        "                        snippets = re.findall(r'<td class=\"result-snippet[^\"]*\">(.*?)</td>', html_content, re.DOTALL)\n",
        "                    if snippets:\n",
        "                        cleaned = []\n",
        "                        for s in snippets[:3]:\n",
        "                            clean_text = re.sub(r'<[^>]+>', '', s)\n",
        "                            clean_text = html.unescape(clean_text)\n",
        "                            cleaned.append(clean_text.strip())\n",
        "                        return \" | \".join(cleaned)\n",
        "            except Exception as e:\n",
        "                logger.error(f\"DuckDuckGo HTML query attempt {attempt + 1} failed: {e}\")\n",
        "        return None\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# 4. IN-PROCESS SECURE SANDBOX & TEACHER\n",
        "# ==========================================\n",
        "\n",
        "_original_import = __import__\n",
        "\n",
        "def secure_import(name, globals=None, locals=None, fromlist=(), level=0):\n",
        "    allowed_modules = {\"math\", \"json\"}\n",
        "    if name in allowed_modules:\n",
        "        return _original_import(name, globals, locals, fromlist, level)\n",
        "    raise ImportError(f\"Import of module '{name}' is restricted inside the sandbox environment.\")\n",
        "\n",
        "\n",
        "def verify_ast_safety_and_structure(code_string: str) -> Tuple[bool, str]:\n",
        "    try:\n",
        "        tree = ast.parse(code_string)\n",
        "    except SyntaxError as e:\n",
        "        return False, f\"AST Pre-check Syntax Error: {str(e)}\"\n",
        "\n",
        "    prohibited_modules = {\n",
        "        \"os\", \"sys\", \"subprocess\", \"shutil\", \"socket\", \"urllib\", \"requests\", \n",
        "        \"http\", \"threading\", \"multiprocessing\", \"ctypes\", \"builtins\", \"importlib\", \"platform\"\n",
        "    }\n",
        "    prohibited_functions = {\n",
        "        \"eval\", \"exec\", \"globals\", \"locals\", \"compile\", \"getattr\", \"setattr\", \"hasattr\", \"delattr\",\n",
        "        \"dir\", \"vars\", \"type\", \"id\"\n",
        "    }\n",
        "    \n",
        "    for node in ast.walk(tree):\n",
        "        if isinstance(node, ast.Import):\n",
        "            for name in node.names:\n",
        "                if name.name in prohibited_modules:\n",
        "                    return False, f\"AST Security Block: Import of restricted module '{name.name}' blocked.\"\n",
        "        elif isinstance(node, ast.ImportFrom):\n",
        "            if node.module in prohibited_modules:\n",
        "                return False, f\"AST Security Block: Import from restricted module '{node.module}' blocked.\"\n",
        "        elif isinstance(node, ast.Call):\n",
        "            if isinstance(node.func, ast.Name) and node.func.id in prohibited_functions:\n",
        "                return False, f\"AST Security Block: Execution of dynamic function '{node.func.id}' blocked.\"\n",
        "        elif isinstance(node, ast.Attribute):\n",
        "            if node.attr.startswith(\"_\"):\n",
        "                return False, f\"AST Security Block: Access to hidden attribute '{node.attr}' blocked.\"\n",
        "        elif isinstance(node, ast.Name):\n",
        "            if node.id.startswith(\"_\") and node.id not in [\"__builtins__\", \"__name__\"]:\n",
        "                return False, f\"AST Security Block: Access to dunder name '{node.id}' blocked.\"\n",
        "        elif isinstance(node, ast.Constant):\n",
        "            if isinstance(node.value, str) and \"__\" in node.value:\n",
        "                return False, f\"AST Security Block: String literals containing double underscores '__' are restricted.\"\n",
        "                        \n",
        "    return True, \"AST structurally validated as safe.\"\n",
        "\n",
        "\n",
        "class SecureInProcessSandbox:\n",
        "    def __init__(self, loop_limit: int = 5000):\n",
        "        self.loop_limit = loop_limit\n",
        "        self.cache = {}\n",
        "\n",
        "\n",
        "class TeacherSandbox(SecureInProcessSandbox):\n",
        "    def __init__(self, search_adapter: Any, loop_limit: int = 5000):\n",
        "        super().__init__(loop_limit)\n",
        "        self.captured_logs = []\n",
        "        self.search_adapter = search_adapter\n",
        "        \n",
        "        def safe_print(*args, **kwargs):\n",
        "            self.captured_logs.append(\" \".join(str(x) for x in args))\n",
        "            \n",
        "        self.safe_builtins = {\n",
        "            \"abs\": abs, \"all\": all, \"any\": any, \"bool\": bool, \"dict\": dict,\n",
        "            \"float\": float, \"int\": int, \"len\": len, \"list\": list, \"map\": map,\n",
        "            \"max\": max, \"min\": min, \"pow\": pow, \"print\": safe_print, \"range\": range,\n",
        "            \"round\": round, \"set\": set, \"str\": str, \"sum\": sum, \"tuple\": tuple,\n",
        "            \"zip\": zip, \"math\": math, \"json\": json, \"TimeoutError\": TimeoutError,\n",
        "            \"Exception\": Exception, \"ValueError\": ValueError, \"TypeError\": TypeError,\n",
        "            \"AssertionError\": AssertionError, \"KeyError\": KeyError, \"IndexError\": IndexError,\n",
        "            \"__import__\": secure_import,\n",
        "            \"search_web\": self.search_adapter.query,\n",
        "            \"calculate_expression\": calculate_expression,\n",
        "            \"binary_search_solver\": binary_search_solver\n",
        "        }\n",
        "\n",
        "    def execute_safely(self, code_string: str, test_assertions: str, variables: List[str]) -> Tuple[bool, Dict[str, Any], str]:\n",
        "        self.captured_logs.clear()\n",
        "        \n",
        "        ast_passed, ast_msg = verify_ast_safety_and_structure(code_string)\n",
        "        if not ast_passed:\n",
        "            return False, {}, f\"Security Block: {ast_msg}\"\n",
        "\n",
        "        combined_hash = hashlib.sha256((code_string + \"_\" + test_assertions).encode(\"utf-8\")).hexdigest()\n",
        "        if combined_hash in self.cache:\n",
        "            return self.cache[combined_hash]\n",
        "\n",
        "        try:\n",
        "            tree = ast.parse(code_string + \"\\n\" + test_assertions)\n",
        "            \n",
        "            transformer = LoopLimiterTransformer(limit=self.loop_limit)\n",
        "            transformed_tree = transformer.visit(tree)\n",
        "            ast.fix_missing_locations(transformed_tree)\n",
        "            \n",
        "            compiled_code = compile(transformed_tree, filename=\"<sandbox>\", mode=\"exec\")\n",
        "            \n",
        "            local_namespace = {}\n",
        "            global_namespace = {\n",
        "                \"__builtins__\": self.safe_builtins,\n",
        "                \"math\": math,\n",
        "                \"json\": json\n",
        "            }\n",
        "            \n",
        "            class SandboxTimeoutException(Exception): pass\n",
        "            \n",
        "            def alarm_handler(signum, frame):\n",
        "                raise SandboxTimeoutException(\"Execution timed out (10s threshold reached).\")\n",
        "                \n",
        "            use_alarm = True\n",
        "            try:\n",
        "                signal.signal(signal.SIGALRM, alarm_handler)\n",
        "            except ValueError:\n",
        "                use_alarm = False\n",
        "                \n",
        "            if use_alarm:\n",
        "                signal.alarm(10)\n",
        "            try:\n",
        "                exec(compiled_code, global_namespace, local_namespace)\n",
        "            except SandboxTimeoutException as te:\n",
        "                raise TimeoutError(str(te))\n",
        "            finally:\n",
        "                if use_alarm:\n",
        "                    signal.alarm(0)\n",
        "            \n",
        "            extracted_vars = {}\n",
        "            for var_name in variables:\n",
        "                if var_name in local_namespace:\n",
        "                    extracted_vars[var_name] = local_namespace[var_name]\n",
        "                elif var_name in global_namespace:\n",
        "                    extracted_vars[var_name] = global_namespace[var_name]\n",
        "            \n",
        "            console_out = \"\\n\".join(self.captured_logs)\n",
        "            log_msg = f\"Execution successful.\\nConsole Logs:\\n{console_out}\" if console_out else \"Execution successful.\"\n",
        "            res = (True, extracted_vars, log_msg)\n",
        "        except AssertionError:\n",
        "            res = (False, {}, \"Teacher Sandbox Feedback: Expected assertion validations failed.\")\n",
        "        except TimeoutError:\n",
        "            res = (False, {}, \"Teacher Sandbox Feedback: Loop limit triggered. Infinite execution loop aborted.\")\n",
        "        except Exception as e:\n",
        "            tb = traceback.format_exc()\n",
        "            cleaned_tb = []\n",
        "            for line in tb.splitlines():\n",
        "                if \"compile(\" in line or \"<sandbox>\" in line or \"exec(\" in line:\n",
        "                    cleaned_tb.append(line)\n",
        "                elif not any(x in line for x in [\"secure_import\", \"execute_safely\"]):\n",
        "                    cleaned_tb.append(line)\n",
        "            trace_details = \"\\n\".join(cleaned_tb[-3:])\n",
        "            res = (False, {}, f\"Teacher Sandbox Feedback - Exception Error:\\n{trace_details}\")\n",
        "\n",
        "        self.cache[combined_hash] = res\n",
        "        return res\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# 5. RESILIENT SAFE DICTIONARY PARSER\n",
        "# ==========================================\n",
        "\n",
        "def safe_literal_dict_eval(node) -> Any:\n",
        "    if isinstance(node, ast.Expression):\n",
        "        return safe_literal_dict_eval(node.body)\n",
        "    elif isinstance(node, ast.Constant):\n",
        "        return node.value\n",
        "    elif isinstance(node, ast.Dict):\n",
        "        return {safe_literal_dict_eval(k): safe_literal_dict_eval(v) for k, v in zip(node.keys, node.values)}\n",
        "    elif isinstance(node, ast.List):\n",
        "        return [safe_literal_dict_eval(el) for el in node.elts]\n",
        "    elif isinstance(node, ast.Tuple):\n",
        "        return tuple(safe_literal_dict_eval(el) for el in node.elts)\n",
        "    elif isinstance(node, ast.UnaryOp):\n",
        "        if isinstance(node.op, ast.USub):\n",
        "            return -safe_literal_dict_eval(node.operand)\n",
        "        elif isinstance(node.op, ast.UAdd):\n",
        "            return safe_literal_dict_eval(node.operand)\n",
        "    raise ValueError(\"Non-literal expression detected.\")\n",
        "\n",
        "\n",
        "def extract_json_block(text: str) -> str:\n",
        "    match = re.search(r\"Prediction:\\s*(\\{.*)\", text, re.DOTALL | re.IGNORECASE)\n",
        "    if not match:\n",
        "        match = re.search(r\"(\\{.*)\", text, re.DOTALL)\n",
        "        if not match:\n",
        "            return \"\"\n",
        "    \n",
        "    content = match.group(1)\n",
        "    brace_count = 0\n",
        "    for idx, char in enumerate(content):\n",
        "        if char == '{':\n",
        "            brace_count += 1\n",
        "        elif char == '}':\n",
        "            brace_count -= 1\n",
        "            if brace_count == 0:\n",
        "                return content[:idx+1]\n",
        "    return \"\"\n",
        "\n",
        "\n",
        "def soft_json_parse(json_str: str) -> Dict[str, Any]:\n",
        "    cleaned = extract_json_block(json_str)\n",
        "    if not cleaned:\n",
        "        return {}\n",
        "    \n",
        "    cleaned = re.sub(r',\\s*\\}', '}', cleaned)\n",
        "    cleaned = re.sub(r',\\s*\\]', ']', cleaned)\n",
        "    \n",
        "    try:\n",
        "        return json.loads(cleaned)\n",
        "    except Exception:\n",
        "        try:\n",
        "            tree = ast.parse(cleaned, mode=\"eval\")\n",
        "            res = safe_literal_dict_eval(tree)\n",
        "            if isinstance(res, dict):\n",
        "                return res\n",
        "        except Exception:\n",
        "            pass\n",
        "    return {}\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# 6. CORPUS SEEDS (REAL COMPLETIONS)\n",
        "# ==========================================\n",
        "\n",
        "MULTI_DOMAIN_SEED_CORPUS = {\n",
        "    \"frontend\": [\n",
        "        {\n",
        "            \"id\": \"fe_01\",\n",
        "            \"question\": \"Implement a coordinate offset scaler function that maps an active element's width to an SVG boundary of 150.0.\",\n",
        "            \"variables\": [\"svg_radius\", \"is_canvas_bound\"],\n",
        "            \"test_assertion\": \"assert svg_radius == 150.0\\nassert is_canvas_bound == True\",\n",
        "            \"code_reference\": \"svg_radius = 150.0\\nis_canvas_bound = True\"\n",
        "        }\n",
        "    ],\n",
        "    \"python\": [\n",
        "        {\n",
        "            \"id\": \"py_01\",\n",
        "            \"question\": \"Implement a cache map tracker storing maximum index bounds.\",\n",
        "            \"variables\": [\"max_tracked_index\", \"is_cached\"],\n",
        "            \"test_assertion\": \"assert max_tracked_index == 50\\nassert is_cached == True\",\n",
        "            \"code_reference\": \"max_tracked_index = 50\\nis_cached = True\"\n",
        "        }\n",
        "    ],\n",
        "    \"security\": [\n",
        "        {\n",
        "            \"id\": \"sec_01\",\n",
        "            \"question\": \"Implement a function to list restricted vulnerability keywords.\",\n",
        "            \"variables\": [\"vulnerability_sinks\", \"is_insecure\"],\n",
        "            \"test_assertion\": \"assert 'pickle.loads' in vulnerability_sinks\\nassert is_insecure == True\",\n",
        "            \"code_reference\": \"vulnerability_sinks = ['pickle.loads', 'eval']\\nis_insecure = True\"\n",
        "        }\n",
        "    ]\n",
        "}\n",
        "\n",
        "\n",
        "class ProceduralCurriculumCompiler:\n",
        "    def __init__(self, corpus: Dict[str, List[Dict[str, Any]]], sandbox: TeacherSandbox):\n",
        "        self.corpus = corpus\n",
        "        self.sandbox = sandbox\n",
        "\n",
        "    def generate_curriculum(self, size: int = 5000) -> List[Dict[str, Any]]:\n",
        "        curriculum = []\n",
        "        domains = list(self.corpus.keys())\n",
        "        \n",
        "        for i in range(size):\n",
        "            domain = domains[i % len(domains)]\n",
        "            templates = self.corpus[domain]\n",
        "            seed = random.choice(templates)\n",
        "            \n",
        "            var_suffix = f\"_delta_idx_{i}\"\n",
        "            question = f\"{seed['question']} (Configuration variant reference: {i * 7})\"\n",
        "            \n",
        "            code_body = seed[\"code_reference\"]\n",
        "            test_assertions = seed[\"test_assertion\"]\n",
        "            \n",
        "            mutated_vars = []\n",
        "            for var in seed[\"variables\"]:\n",
        "                new_var = f\"{var}{var_suffix}\"\n",
        "                mutated_vars.append(new_var)\n",
        "                code_body = code_body.replace(var, new_var)\n",
        "                test_assertions = test_assertions.replace(var, new_var)\n",
        "\n",
        "            success, ext_vars, _ = self.sandbox.execute_safely(code_body, test_assertions, mutated_vars)\n",
        "            prediction_json = json.dumps(ext_vars) if success else \"{}\"\n",
        "\n",
        "            sft_reference = (\n",
        "                f\"<think>\\n\"\n",
        "                f\"Prediction: {prediction_json}\\n\"\n",
        "                f\"<dream_code>\\n\"\n",
        "                f\"{code_body}\\n\"\n",
        "                f\"</dream_code>\\n\"\n",
        "                f\"<tool_response>SUCCESS: Sandbox loop completed assertions cleanly.</tool_response>\\n\"\n",
        "                f\"<conscious_reflection>\\n\"\n",
        "                f\"The physical environment metrics match internal variables. Satiated.\\n\"\n",
        "                f\"</conscious_reflection>\\n\"\n",
        "                f\"</think>\\n\"\n",
        "                f\"{code_body}\"\n",
        "            )\n",
        "            \n",
        "            curriculum.append({\n",
        "                \"domain\": domain,\n",
        "                \"question\": question,\n",
        "                \"variables\": mutated_vars,\n",
        "                \"sft_reference\": sft_reference,\n",
        "                \"test_assertion\": test_assertions,\n",
        "                \"system_prompt\": \"System: You are a secure execution assistant.\"\n",
        "            })\n",
        "            \n",
        "        return curriculum\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# 8. DYNAMIC DATA INGESTOR\n",
        "# ==========================================\n",
        "\n",
        "class DynamicDataIngestor:\n",
        "    def __init__(self, compiler: ProceduralCurriculumCompiler, sandbox: TeacherSandbox):\n",
        "        self.compiler = compiler\n",
        "        self.sandbox = sandbox\n",
        "\n",
        "    def load_training_dataset(self, file_path: str = None) -> List[Dict[str, Any]]:\n",
        "        if file_path and os.path.exists(file_path):\n",
        "            try:\n",
        "                with open(file_path, \"r\", encoding=\"utf-8\") as f:\n",
        "                    data = json.load(f)\n",
        "                if isinstance(data, list) and len(data) > 0:\n",
        "                    logger.info(f\"Loaded {len(data)} items from custom dataset at {file_path}\")\n",
        "                    return data\n",
        "            except Exception as e:\n",
        "                logger.error(f\"Failed to load custom dataset from {file_path}: {e}\")\n",
        "\n",
        "        logger.info(\"[INFO] Direct custom dataset file not found or corrupted. Compiling fallback procedural curriculum...\")\n",
        "        return self.compiler.generate_curriculum(500)\n",
        "\n",
        "\n",
        "# ==============================================================================\n",
        "# 9. V3 EXTRAS: MOCK GENERATION STOPPING CRITERIA & parallel GPU rollout\n",
        "# ==============================================================================\n",
        "\n",
        "class TagClosingStoppingCriteria(StoppingCriteria):\n",
        "    \"\"\"\n",
        "    Stops token generation instantly once the target closing sequence has been output.\n",
        "    Reduces redundant token output by up to 80% to accelerate training runs.\n",
        "    \"\"\"\n",
        "    def __init__(self, tokenizer, closing_tag=\"</conscious_reflection>\"):\n",
        "        self.tokenizer = tokenizer\n",
        "        self.closing_tag = closing_tag\n",
        "        \n",
        "    def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor, **kwargs) -> bool:\n",
        "        if input_ids.shape[1] < 12:\n",
        "            return False\n",
        "        last_tokens = input_ids[0, -12:]\n",
        "        decoded = self.tokenizer.decode(last_tokens, skip_special_tokens=True)\n",
        "        return self.closing_tag in decoded\n",
        "\n",
        "\n",
        "def validate_layout_xml_structure(text: str) -> Tuple[bool, str]:\n",
        "    \"\"\"\n",
        "    Verifies that the generated layout contains valid, nested XML tag formats.\n",
        "    \"\"\"\n",
        "    opened_tags = []\n",
        "    tags = [\"think\", \"dream_code\", \"tool_response\", \"conscious_reflection\", \"critique\"]\n",
        "    pattern = re.compile(r\"<(/?)(think|dream_code|tool_response|conscious_reflection|critique)>\")\n",
        "    \n",
        "    for match in pattern.finditer(text):\n",
        "        is_closing = bool(match.group(1))\n",
        "        tag_name = match.group(2)\n",
        "        if not is_closing:\n",
        "            opened_tags.append(tag_name)\n",
        "        else:\n",
        "            if not opened_tags or opened_tags[-1] != tag_name:\n",
        "                return False, f\"Layout Error: Mismatched tag sequence. Attempted to close '{tag_name}' when '{opened_tags[-1] if opened_tags else 'None'}' was open.\"\n",
        "            opened_tags.pop()\n",
        "            \n",
        "    if opened_tags:\n",
        "        return False, f\"Layout Error: Unclosed tags remaining: {opened_tags}\"\n",
        "    return True, \"XML tags structurally validated.\"\n",
        "\n",
        "\n",
        "# ==============================================================================\n",
        "# 10. DUAL GPU INITIALIZER & PARALLEL EXECUTION\n",
        "# ==============================================================================\n",
        "\n",
        "def load_dual_gpu_models(model_name: str, max_seq_length: int) -> Tuple[Any, Any, Any]:\n",
        "    \"\"\"\n",
        "    Instantiates models on cuda:0 and cuda:1 concurrently for parallel rollout generation.\n",
        "    Falls back gracefully to a single GPU if only one device is available.\n",
        "    \"\"\"\n",
        "    print(f\"[INFO] Initializing main GPU model on cuda:0...\")\n",
        "    model_gpu0, tokenizer = FastLanguageModel.from_pretrained(\n",
        "        model_name=model_name,\n",
        "        max_seq_length=max_seq_length,\n",
        "        load_in_4bit=True,\n",
        "        fast_inference=False,\n",
        "        trust_remote_code=True,\n",
        "        device_map=\"cuda:0\"\n",
        "    )\n",
        "    \n",
        "    # Attempt loading secondary GPU copy\n",
        "    try:\n",
        "        if torch.cuda.device_count() > 1:\n",
        "            print(f\"[INFO] Secondary GPU detected. Loading generation clone on cuda:1...\")\n",
        "            model_gpu1, _ = FastLanguageModel.from_pretrained(\n",
        "                model_name=model_name,\n",
        "                max_seq_length=max_seq_length,\n",
        "                load_in_4bit=True,\n",
        "                fast_inference=False,\n",
        "                trust_remote_code=True,\n",
        "                device_map=\"cuda:1\"\n",
        "            )\n",
        "            print(\"[SUCCESS] Loaded model instances on both cuda:0 and cuda:1!\")\n",
        "        else:\n",
        "            print(\"[INFO] Single GPU detected. Running all steps on cuda:0.\")\n",
        "            model_gpu1 = model_gpu0\n",
        "    except Exception as e:\n",
        "        logger.warning(f\"[WARNING] Dual-GPU loading failed. Falling back to single GPU configuration. Details: {e}\")\n",
        "        model_gpu1 = model_gpu0\n",
        "        \n",
        "    return model_gpu0, model_gpu1, tokenizer\n",
        "\n",
        "\n",
        "# ==============================================================================\n",
        "# 11. DENSE REWARD MODELING & POLICY UPDATE\n",
        "# ==============================================================================\n",
        "\n",
        "def compute_dense_reward(turn1_text: str, passed: bool, xml_valid: bool, has_critique: bool) -> float:\n",
        "    \"\"\"\n",
        "    Computes a multi-dimensional continuous reward signal to guide policy updates.\n",
        "    \"\"\"\n",
        "    reward = 0.0\n",
        "    if passed:\n",
        "        reward += 1.0  # Execution success\n",
        "    if xml_valid:\n",
        "        reward += 0.3  # Syntax correctness\n",
        "    if has_critique:\n",
        "        reward += 0.2  # Formatting reflection\n",
        "        \n",
        "    # Apply token length constraints to prevent endless rambling\n",
        "    token_len = len(turn1_text.split())\n",
        "    if token_len > 0:\n",
        "        reward -= 0.05 * math.log(token_len)\n",
        "        \n",
        "    return reward\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# 12. SYMMETRICAL CO-TRAINING ENGINE (V3 GRPO)\n",
        "# ==========================================\n",
        "\n",
        "def run_symmetrical_agi_pipeline(custom_dataset_path: str = None, config: TrainingConfig = None):\n",
        "    if config is None:\n",
        "        config = TrainingConfig()\n",
        "        \n",
        "    import os\n",
        "    model_name = os.environ.get(\"MODEL_NAME\", config.model_name)\n",
        "    start_idx = int(os.environ.get(\"START_IDX\", \"0\"))\n",
        "    \n",
        "    # Initialize real search adapter\n",
        "    search_adapter = RealSearchAdapter()\n",
        "    \n",
        "    # Instantiate the base models on dual GPUs\n",
        "    model_gpu0, model_gpu1, tokenizer = load_dual_gpu_models(model_name, config.max_seq_length)\n",
        "    \n",
        "    # Load targets\n",
        "    discovered_projections = []\n",
        "    for name, module in model_gpu0.named_modules():\n",
        "        if \"proj\" in name or \"linear\" in name:\n",
        "            if not any(x in name for x in [\"bias\", \"norm\", \"embed\"]):\n",
        "                discovered_projections.append(name.split(\".\")[-1])\n",
        "            \n",
        "    discovered_projections = list(set(discovered_projections))\n",
        "    if not discovered_projections:\n",
        "        discovered_projections = [\"q_proj\", \"k_proj\", \"v_proj\", \"o_proj\", \"gate_proj\", \"up_proj\", \"down_proj\"]\n",
        "        \n",
        "    # Configure trainable LoRA adapters on main GPU (GPU 0)\n",
        "    model_gpu0 = FastLanguageModel.get_peft_model(\n",
        "        model_gpu0,\n",
        "        r=config.lora_r,\n",
        "        target_modules=discovered_projections,\n",
        "        lora_alpha=config.lora_alpha,\n",
        "        use_gradient_checkpointing=\"unsloth\",\n",
        "        random_state=42,\n",
        "    )\n",
        "    \n",
        "    optimizer = AdamW(model_gpu0.parameters(), lr=config.learning_rate, weight_decay=config.weight_decay)\n",
        "    sandbox = TeacherSandbox(search_adapter=search_adapter)\n",
        "    compiler = ProceduralCurriculumCompiler(MULTI_DOMAIN_SEED_CORPUS, sandbox)\n",
        "    ingestor = DynamicDataIngestor(compiler, sandbox)\n",
        "    \n",
        "    raw_dataset = ingestor.load_training_dataset(custom_dataset_path)\n",
        "    random.seed(42) # Ensure deterministic shuffling across split training runs\n",
        "    random.shuffle(raw_dataset)\n",
        "    \n",
        "    split_boundary = int(len(raw_dataset) * config.train_split_ratio)\n",
        "    train_dataset = raw_dataset[:split_boundary]\n",
        "    eval_dataset = raw_dataset[split_boundary:]\n",
        "    print(f\"[INFO] Segmented splits. Training: {len(train_dataset)} | Evaluation: {len(eval_dataset)}\")\n",
        "    \n",
        "    end_idx = int(os.environ.get(\"END_IDX\", str(len(train_dataset))))\n",
        "    training_slice = train_dataset[start_idx:end_idx]\n",
        "    print(f\"[INFO] Selected training slice: index {start_idx} to {end_idx} (Size: {len(training_slice)})\")\n",
        "    \n",
        "    metrics = {\n",
        "        \"grpo_losses\": [],\n",
        "        \"sft_losses\": [],\n",
        "        \"simpo_total_candidates\": 0,\n",
        "        \"simpo_t1_pass\": 0,\n",
        "        \"simpo_t2_pass\": 0,\n",
        "        \"eval_pass_rate\": 0.0\n",
        "    }\n",
        "    \n",
        "    print(\"\\n\" + \"=\"*80)\n",
        "    print(f\"[RUN 1 INITIALIZED] Dual-GPU GRPO Symmetrical Alignment Pass\")\n",
        "    print(\"=\"*80)\n",
        "    \n",
        "    # ----------------------------------------------------------------------\n",
        "    # PHASE 1: BATCHED TRAJECTORY GENERATION (Consolidated Dual-GPU Eval Mode)\n",
        "    # ----------------------------------------------------------------------\n",
        "    try:\n",
        "        FastLanguageModel.for_inference(model_gpu0)\n",
        "    except Exception:\n",
        "        pass\n",
        "    model_gpu0.eval()\n",
        "    if model_gpu1 is not model_gpu0:\n",
        "        try:\n",
        "            FastLanguageModel.for_inference(model_gpu1)\n",
        "        except Exception:\n",
        "            pass\n",
        "        model_gpu1.eval()\n",
        "        \n",
        "    batched_trajectories = []\n",
        "    stopping_criteria = StoppingCriteriaList([TagClosingStoppingCriteria(tokenizer)])\n",
        "    \n",
        "    print(\"[INFO] Executing Symmetrical Group Rollouts in Parallel across both GPUs...\")\n",
        "    \n",
        "    # Process dataset in groups of prompts\n",
        "    for idx, sample in enumerate(tqdm(training_slice, desc=\"GRPO Rollouts\")):\n",
        "        logger.info(f\"===> [Rollout {idx+1}/{len(training_slice)}] Starting trajectory rollout for domain: {sample.get('domain', 'unknown')}\")\n",
        "        logger.info(f\"Question snippet: '{sample['question'][:80]}...'\")\n",
        "        \n",
        "        prompt_text = f\"{sample['system_prompt']}\\nUser: {sample['question']}\\nAssistant: <think>\"\n",
        "        \n",
        "        metrics[\"simpo_total_candidates\"] += config.G_group_size\n",
        "        \n",
        "        # Parallel candidate generation on GPU 0 and GPU 1\n",
        "        prompts_batch = [prompt_text] * config.G_group_size\n",
        "        \n",
        "        # Sub-divide prompts between the two GPU devices\n",
        "        prompts_gpu0 = prompts_batch[:config.G_group_size // 2]\n",
        "        prompts_gpu1 = prompts_batch[config.G_group_size // 2:]\n",
        "        \n",
        "        def run_inference(model, device_name, prompts_subset):\n",
        "            if not prompts_subset:\n",
        "                return []\n",
        "            inputs = tokenizer(prompts_subset, return_tensors=\"pt\", padding=True).to(device_name)\n",
        "            prompt_len = inputs[\"input_ids\"].shape[1]\n",
        "            with torch.no_grad():\n",
        "                with torch.cuda.amp.autocast():\n",
        "                    out = model.generate(\n",
        "                        **inputs,\n",
        "                        max_new_tokens=config.max_new_tokens,\n",
        "                        do_sample=True,\n",
        "                        temperature=0.85,\n",
        "                        pad_token_id=tokenizer.eos_token_id,\n",
        "                        stopping_criteria=stopping_criteria,\n",
        "                        use_cache=True\n",
        "                    )\n",
        "            return [tokenizer.decode(out[i][prompt_len:], skip_special_tokens=True) for i in range(len(prompts_subset))]\n",
        "            \n",
        "        with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:\n",
        "            fut0 = executor.submit(run_inference, model_gpu0, \"cuda:0\", prompts_gpu0)\n",
        "            fut1 = executor.submit(run_inference, model_gpu1, \"cuda:1\" if model_gpu1 is not model_gpu0 else \"cuda:0\", prompts_gpu1)\n",
        "            \n",
        "            out_gpu0 = fut0.result()\n",
        "            out_gpu1 = fut1.result()\n",
        "            \n",
        "        completions = out_gpu0 + out_gpu1\n",
        "        rewards = []\n",
        "        \n",
        "        # Evaluate each candidate in the group\n",
        "        for c, turn1_text in enumerate(completions):\n",
        "            # XML Layout Verification\n",
        "            xml_valid, xml_err = validate_layout_xml_structure(turn1_text)\n",
        "            \n",
        "            # Sandbox Code Execution\n",
        "            dream_match = re.search(r\"<dream_code>(.*?)</dream_code>\", turn1_text, re.DOTALL)\n",
        "            code_block = dream_match.group(1).strip() if dream_match else \"\"\n",
        "            passed, ext_vars, log_msg = sandbox.execute_safely(code_block, sample[\"test_assertion\"], sample[\"variables\"])\n",
        "            \n",
        "            logger.info(f\"  Candidate {c+1} Execution: {'PASSED' if passed else 'FAILED'} | XML Valid: {xml_valid}\")\n",
        "            \n",
        "            # SFT Correction Backtracking if Turn 1 failed\n",
        "            has_critique = False\n",
        "            if not passed:\n",
        "                turn2_prompt = (\n",
        "                    f\"{prompt_text}{turn1_text}\\n\"\n",
        "                    f\"<tool_response>{log_msg}</tool_response>\\n\"\n",
        "                    f\"<critique>\\n\"\n",
        "                    f\"The code failed compiler execution. I will write a critique and re-try.\\n\"\n",
        "                    f\"</critique>\\n\"\n",
        "                    f\"<conscious_reflection>\\n\"\n",
        "                    f\"Correct references.\\n\"\n",
        "                    f\"</conscious_reflection>\\n\"\n",
        "                    f\"<think>\"\n",
        "                )\n",
        "                inputs2 = tokenizer([turn2_prompt], return_tensors=\"pt\").to(\"cuda:0\")\n",
        "                prompt_len2 = inputs2[\"input_ids\"].shape[1]\n",
        "                with torch.no_grad():\n",
        "                    with torch.cuda.amp.autocast():\n",
        "                        out2 = model_gpu0.generate(\n",
        "                            **inputs2,\n",
        "                            max_new_tokens=config.max_new_tokens // 2,\n",
        "                            do_sample=True,\n",
        "                            temperature=0.75,\n",
        "                            pad_token_id=tokenizer.eos_token_id,\n",
        "                            use_cache=True\n",
        "                        )\n",
        "                turn2_text = tokenizer.decode(out2[0][prompt_len2:], skip_special_tokens=True)\n",
        "                \n",
        "                # Check Turn 2 code\n",
        "                dream_match2 = re.search(r\"<dream_code>(.*?)</dream_code>\", turn2_text, re.DOTALL)\n",
        "                code_block2 = dream_match2.group(1).strip() if dream_match2 else \"\"\n",
        "                passed2, _, _ = sandbox.execute_safely(code_block2, sample[\"test_assertion\"], sample[\"variables\"])\n",
        "                \n",
        "                if passed2:\n",
        "                    passed = True\n",
        "                    has_critique = True\n",
        "                    turn1_text = f\"{turn1_text}\\n<tool_response>{log_msg}</tool_response>\\n{turn2_text}\"\n",
        "                    completions[c] = turn1_text\n",
        "                    metrics[\"simpo_t2_pass\"] += 1\n",
        "            else:\n",
        "                metrics[\"simpo_t1_pass\"] += 1\n",
        "                \n",
        "            r = compute_dense_reward(turn1_text, passed, xml_valid, has_critique)\n",
        "            rewards.append(r)\n",
        "            \n",
        "        batched_trajectories.append((prompt_text, completions, rewards))\n",
        "        \n",
        "        # Flush CUDA memory\n",
        "        del prompts_gpu0, prompts_gpu1\n",
        "        gc.collect()\n",
        "        torch.cuda.empty_cache()\n",
        "\n",
        "    # ----------------------------------------------------------------------\n",
        "    # PHASE 2: GRPO OPTIMIZATION LOOP WITH REPLAY BUFFER (Off-Policy Speedup)\n",
        "    # ----------------------------------------------------------------------\n",
        "    try:\n",
        "        FastLanguageModel.for_training(model_gpu0)\n",
        "    except Exception:\n",
        "        pass\n",
        "    model_gpu0.train()\n",
        "    optimizer.zero_grad()\n",
        "    \n",
        "    print(f\"[INFO] Phase 2: Computing GRPO Clipped Policy Gradients (Epochs: {config.num_epochs})...\")\n",
        "    \n",
        "    # Replay Buffer Epochs\n",
        "    for epoch in range(config.num_epochs):\n",
        "        print(f\"\\n[INFO] --- GRPO Optimization Epoch {epoch+1}/{config.num_epochs} ---\")\n",
        "        \n",
        "        for idx, (prompt_text, completions, rewards) in enumerate(tqdm(batched_trajectories, desc=f\"GRPO Epoch {epoch+1}\")):\n",
        "            try:\n",
        "                sample = training_slice[idx]\n",
        "                \n",
        "                # Compute normalized relative advantages across group\n",
        "                r_tensor = torch.tensor(rewards, dtype=torch.float32)\n",
        "                r_mean = r_tensor.mean()\n",
        "                r_std = r_tensor.std() if len(r_tensor) > 1 else torch.tensor(0.0)\n",
        "                advantages = [(r - r_mean) / (r_std + 1e-8) for r in rewards]\n",
        "                \n",
        "                logger.info(f\"===> [GRPO Step {idx+1}/{len(batched_trajectories)}] Optimizing advantages: {[float(a) for a in advantages]}\")\n",
        "                \n",
        "                # Dynamic SFT stabilization loss\n",
        "                sft_prompt = f\"{prompt_text}{sample['sft_reference']}\"\n",
        "                sft_inputs = tokenizer([sft_prompt], return_tensors=\"pt\", padding=True).to(\"cuda:0\")\n",
        "                loss_sft = model_gpu0(**sft_inputs, labels=sft_inputs[\"input_ids\"]).loss\n",
        "                \n",
        "                loss_scaled_sft = loss_sft / config.accumulation_steps\n",
        "                loss_scaled_sft.backward()\n",
        "                \n",
        "                # Policy gradient optimization for each candidate in group\n",
        "                for c, turn1_text in enumerate(completions):\n",
        "                    adv = advantages[c]\n",
        "                    \n",
        "                    # Compute log probabilities\n",
        "                    log_prob = get_sequence_log_prob(model_gpu0, tokenizer, prompt_text, turn1_text)\n",
        "                    \n",
        "                    # Policy Gradient surrogate loss (clipped advantage optimization)\n",
        "                    ratio = torch.exp(log_prob)  # Reference-free policy ratio\n",
        "                    surr1 = ratio * adv\n",
        "                    surr2 = torch.clamp(ratio, 1.0 - 0.2, 1.0 + 0.2) * adv\n",
        "                    loss_policy = -torch.min(surr1, surr2)\n",
        "                    \n",
        "                    # Symmetrical joint loss with KL penalty\n",
        "                    loss_joint = (config.lambda_symmetry * loss_sft) + ((1.0 - config.lambda_symmetry) * loss_policy)\n",
        "                    loss_scaled_joint = loss_joint / (config.accumulation_steps * config.G_group_size)\n",
        "                    loss_scaled_joint.backward()\n",
        "                    \n",
        "                    metrics[\"grpo_losses\"].append(loss_joint.item())\n",
        "                    \n",
        "                if (idx + 1) % config.accumulation_steps == 0 or (idx + 1) == len(batched_trajectories):\n",
        "                    logger.info(\"  Gradient Accumulation limit met. Updating weights...\")\n",
        "                    torch.nn.utils.clip_grad_norm_(model_gpu0.parameters(), config.max_grad_norm)\n",
        "                    optimizer.step()\n",
        "                    optimizer.zero_grad()\n",
        "                    \n",
        "            except Exception as grpo_err:\n",
        "                logger.warning(f\"  GRPO Optimization step bypassed at index {idx}. Details: {grpo_err}\")\n",
        "                continue\n",
        "\n",
        "    # Save Phase 1 Checkpoint (GRPO)\n",
        "    phase1_dir = os.path.join(config.save_checkpoint_dir, \"phase1_grpo\")\n",
        "    os.makedirs(phase1_dir, exist_ok=True)\n",
        "    model_gpu0.save_pretrained(phase1_dir)\n",
        "    tokenizer.save_pretrained(phase1_dir)\n",
        "    print(f\"[SUCCESS] Phase 1 (GRPO) checkpoint saved to: {phase1_dir}\")\n",
        "    \n",
        "    # Flush VRAM\n",
        "    gc.collect()\n",
        "    torch.cuda.empty_cache()\n",
        "    \n",
        "    active_v0_weights = {k: v.clone().cpu() for k, v in model_gpu0.named_parameters() if v.requires_grad}\n",
        "\n",
        "    # -------------------------------------------------------------\n",
        "    # PHASE 3: CONVEX STABILIZATION PASS\n",
        "    # -------------------------------------------------------------\n",
        "    print(\"\\n\" + \"=\"*80)\n",
        "    print(\"[RUN 2 INITIALIZED] Convex Formatting Stabilization Pass\")\n",
        "    print(\"=\"*80)\n",
        "    \n",
        "    optimizer = AdamW(model_gpu0.parameters(), lr=config.learning_rate * 0.8, weight_decay=config.weight_decay * 5)\n",
        "    try:\n",
        "        FastLanguageModel.for_training(model_gpu0)\n",
        "    except Exception:\n",
        "        pass\n",
        "    model_gpu0.train()\n",
        "    optimizer.zero_grad()\n",
        "    \n",
        "    for idx, sample in enumerate(tqdm(training_slice, desc=\"SFT Training\")):\n",
        "        try:\n",
        "            logger.info(f\"===> [SFT Step {idx+1}/{len(training_slice)}] Processing domain: {sample.get('domain', 'unknown')}\")\n",
        "            sft_prompt = f\"{sample['system_prompt']}\\nUser: {sample['question']}\\nAssistant: {sample['sft_reference']}\"\n",
        "            sft_inputs = tokenizer([sft_prompt], return_tensors=\"pt\", padding=True).to(\"cuda:0\")\n",
        "            loss_sft = model_gpu0(**sft_inputs, labels=sft_inputs[\"input_ids\"]).loss\n",
        "            \n",
        "            logger.info(f\"  SFT Loss: {loss_sft.item():.4f}\")\n",
        "            loss_scaled = loss_sft / config.accumulation_steps\n",
        "            loss_scaled.backward()\n",
        "            \n",
        "            metrics[\"sft_losses\"].append(loss_sft.item())\n",
        "            \n",
        "            if (idx + 1) % config.accumulation_steps == 0 or (idx + 1) == len(training_slice):\n",
        "                logger.info(\"  Gradient Accumulation limit met. Performing SFT optimizer update...\")\n",
        "                torch.nn.utils.clip_grad_norm_(model_gpu0.parameters(), config.max_grad_norm)\n",
        "                optimizer.step()\n",
        "                optimizer.zero_grad()\n",
        "        except Exception as sample_err:\n",
        "            logger.warning(f\"  Round 2 failed for idx {idx}. Details: {sample_err}\")\n",
        "            continue\n",
        "        \n",
        "    active_v1_weights = {k: v.clone().cpu() for k, v in model_gpu0.named_parameters() if v.requires_grad}\n",
        "    \n",
        "    # Save Phase 2 Checkpoint (SFT)\n",
        "    phase2_dir = os.path.join(config.save_checkpoint_dir, \"phase2_sft\")\n",
        "    os.makedirs(phase2_dir, exist_ok=True)\n",
        "    model_gpu0.save_pretrained(phase2_dir)\n",
        "    tokenizer.save_pretrained(phase2_dir)\n",
        "    print(f\"[SUCCESS] Phase 2 (SFT) checkpoint saved to: {phase2_dir}\")\n",
        "    \n",
        "    # Execute SLERP Merge on isolated parameters\n",
        "    merged_weights = run_slerp_adapter_merge(model_gpu0, active_v0_weights, active_v1_weights, t=0.5)\n",
        "    \n",
        "    # Restore merged weights in-place\n",
        "    for name, param in model_gpu0.named_parameters():\n",
        "        if name in merged_weights:\n",
        "            param.data.copy_(merged_weights[name].to(param.device))\n",
        "            \n",
        "    print(\"[SUCCESS] Slerp-merged weights successfully loaded into active model registers.\")\n",
        "    \n",
        "    # Save Phase 3 Checkpoint (Merged)\n",
        "    phase3_dir = os.path.join(config.save_checkpoint_dir, \"phase3_merged\")\n",
        "    os.makedirs(phase3_dir, exist_ok=True)\n",
        "    model_gpu0.save_pretrained(phase3_dir)\n",
        "    tokenizer.save_pretrained(phase3_dir)\n",
        "    print(f\"[SUCCESS] Phase 3 (Merged) checkpoint saved to: {phase3_dir}\")\n",
        "\n",
        "    # ==========================================\n",
        "    # 13. EVALUATION MATRIX REPORT\n",
        "    # ==========================================\n",
        "    print(\"\\n\" + \"=\"*80)\n",
        "    print(\"[EVALUATION INITIALIZED] Running Symmetrical Validation Matrix\")\n",
        "    print(\"=\"*80)\n",
        "    try:\n",
        "        FastLanguageModel.for_inference(model_gpu0)\n",
        "    except Exception:\n",
        "        pass\n",
        "    model_gpu0.eval()\n",
        "    eval_successes = 0\n",
        "    \n",
        "    for sample in eval_dataset[:30]:\n",
        "        prompt_text = f\"{sample['system_prompt']}\\nUser: {sample['question']}\\nAssistant: <think>\"\n",
        "        inputs = tokenizer([prompt_text], return_tensors=\"pt\").to(\"cuda:0\")\n",
        "        prompt_len = inputs[\"input_ids\"].shape[1]\n",
        "        with torch.no_grad():\n",
        "            with torch.cuda.amp.autocast():\n",
        "                out = model_gpu0.generate(\n",
        "                    **inputs,\n",
        "                    max_new_tokens=config.max_new_tokens,\n",
        "                    pad_token_id=tokenizer.eos_token_id,\n",
        "                    stopping_criteria=stopping_criteria,\n",
        "                    use_cache=True\n",
        "                )\n",
        "        eval_text = tokenizer.decode(out[0][prompt_len:], skip_special_tokens=True)\n",
        "        dream_match = re.search(r\"<dream_code>(.*?)</dream_code>\", eval_text, re.DOTALL)\n",
        "        code_block = dream_match.group(1).strip() if dream_match else \"\"\n",
        "        passed, _, _ = sandbox.execute_safely(code_block, sample[\"test_assertion\"], sample[\"variables\"])\n",
        "        if passed:\n",
        "            eval_successes += 1\n",
        "            \n",
        "    metrics[\"eval_pass_rate\"] = eval_successes / min(30, len(eval_dataset)) if len(eval_dataset) > 0 else 0.0\n",
        "    \n",
        "    grpo_avg_loss = sum(metrics[\"grpo_losses\"]) / len(metrics[\"grpo_losses\"]) if metrics[\"grpo_losses\"] else 0.0\n",
        "    sft_avg_loss = sum(metrics[\"sft_losses\"]) / len(metrics[\"sft_losses\"]) if metrics[\"sft_losses\"] else 0.0\n",
        "    simpo_t1_rate = metrics[\"simpo_t1_pass\"] / metrics[\"simpo_total_candidates\"] if metrics[\"simpo_total_candidates\"] else 0.0\n",
        "    simpo_t2_rate = metrics[\"simpo_t2_pass\"] / metrics[\"simpo_total_candidates\"] if metrics[\"simpo_total_candidates\"] else 0.0\n",
        "\n",
        "    print(\"\\n\" + \"=\"*65)\n",
        "    print(f\"{'Metric Description':<40} | {'Value / Rate':<20}\")\n",
        "    print(\"-\" * 65)\n",
        "    print(f\"{'GRPO Active Loss (Mean)':<40} | {grpo_avg_loss:<20.4f}\")\n",
        "    print(f\"{'SimPO Turn 1 Program Pass Rate':<40} | {simpo_t1_rate:<20.2%}\")\n",
        "    print(f\"{'SimPO Turn 2 Program Pass Rate':<40} | {simpo_t2_rate:<20.2%}\")\n",
        "    print(f\"{'SFT Stabilization Loss (Mean)':<40} | {sft_avg_loss:<20.4f}\")\n",
        "    print(f\"{'Evaluation Split Assertion Pass Rate':<40} | {metrics['eval_pass_rate']:<20.2%}\")\n",
        "    print(\"=\"*65 + \"\\n\")\n",
        "    \n",
        "    # Export fully compiled LoRA model merged directly as standard 16bit HF model first\n",
        "    model_gpu0.save_pretrained_merged(\"agi_model_merged_16bit\", tokenizer, save_method=\"merged_16bit\")\n",
        "    \n",
        "    # Fast pre-compiled GGUF export bypassing slow manual compiling steps\n",
        "    try:\n",
        "        model_gpu0.save_pretrained_gguf(\"agi_v10_output\", tokenizer, quantization_method=\"f16\")\n",
        "        print(\"[SUCCESS] GGUF compile using precompiled f16 quantization complete.\")\n",
        "    except Exception as e:\n",
        "        print(f\"[WARNING] GGUF pre-compiled conversion bypassed. Trace: {e}\")\n",
        "        \n",
        "    try:\n",
        "        model_gpu0.save_pretrained_gguf(\"agi_v10_output\", tokenizer, quantization_method=\"q4_k_m\")\n",
        "        print(\"[SUCCESS] GGUF compile using precompiled q4_k_m quantization complete.\")\n",
        "    except Exception as e:\n",
        "        print(f\"[WARNING] GGUF pre-compiled q4_k_m conversion bypassed. Trace: {e}\")\n",
        "        \n",
        "    return model_gpu0, tokenizer, search_adapter\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# 13. GRADIO INTERACTIVE ACTIVE-DEBUGGING UI\n",
        "# ==========================================\n",
        "\n",
        "def launch_gradio_interactive_ui(model, tokenizer, search_adapter: RealSearchAdapter):\n",
        "    if not _GRADIO_AVAILABLE:\n",
        "        print(\"\\n[WARNING] Gradio is not installed. Falling back to console chat loop...\")\n",
        "        print(\"Type 'exit' or 'quit' to end the session.\\n\")\n",
        "        sandbox_evaluator = TeacherSandbox(search_adapter=search_adapter)\n",
        "        model.eval()\n",
        "        \n",
        "        while True:\n",
        "            try:\n",
        "                user_message = input(\"User: \")\n",
        "                if user_message.lower() in [\"exit\", \"quit\"]:\n",
        "                    break\n",
        "                    \n",
        "                active_prompt = (\n",
        "                    \"System: You are an advanced AI assistant specialized in reasoning and self-correction.\\n\"\n",
        "                    f\"User: {user_message}\\nAssistant: <think>\"\n",
        "                )\n",
        "                \n",
        "                inputs = tokenizer([active_prompt], return_tensors=\"pt\").to(\"cuda\")\n",
        "                prompt_len = inputs[\"input_ids\"].shape[1]\n",
        "                \n",
        "                # Turn 1\n",
        "                with torch.no_grad():\n",
        "                    out = model.generate(\n",
        "                        **inputs,\n",
        "                        max_new_tokens=1024,\n",
        "                        pad_token_id=tokenizer.eos_token_id,\n",
        "                        use_cache=True\n",
        "                    )\n",
        "                turn1_text = tokenizer.decode(out[0][prompt_len:], skip_special_tokens=True)\n",
        "                \n",
        "                # Extract code & execute\n",
        "                dream_match = re.search(r\"<dream_code>(.*?)</dream_code>\", turn1_text, re.DOTALL)\n",
        "                dream_code = dream_match.group(1).strip() if dream_match else \"\"\n",
        "                \n",
        "                test_assertions = \"assert True\"\n",
        "                variables = []\n",
        "                success, _, sandbox_terminal_logs = sandbox_evaluator.execute_safely(dream_code, test_assertions, variables)\n",
        "                \n",
        "                print(f\"Assistant: <think>\\n{turn1_text}\")\n",
        "                \n",
        "                if not success:\n",
        "                    # Turn 2: Self-correction trigger\n",
        "                    turn2_prompt = (\n",
        "                        f\"{active_prompt}{turn1_text}\\n\"\n",
        "                        f\"<tool_response>{sandbox_terminal_logs}</tool_response>\\n\"\n",
        "                        f\"<critique>\\n\"\n",
        "                        f\"The code failed compiler execution. I will diagnose and correct.\\n\"\n",
        "                        f\"</critique>\\n\"\n",
        "                        f\"<conscious_reflection>\\n\"\n",
        "                        f\"Correction strategy.\\n\"\n",
        "                        f\"</conscious_reflection>\\n\"\n",
        "                        f\"<think>\"\n",
        "                    )\n",
        "                    inputs2 = tokenizer([turn2_prompt], return_tensors=\"pt\").to(\"cuda\")\n",
        "                    prompt_len2 = inputs2[\"input_ids\"].shape[1]\n",
        "                    with torch.no_grad():\n",
        "                        out2 = model.generate(\n",
        "                            **inputs2,\n",
        "                            max_new_tokens=1024,\n",
        "                            pad_token_id=tokenizer.eos_token_id,\n",
        "                            use_cache=True\n",
        "                        )\n",
        "                    turn2_text = tokenizer.decode(out2[0][prompt_len2:], skip_special_tokens=True)\n",
        "                    print(f\"\\n[Turn 2 Self-Correction]\\n{turn2_text}\")\n",
        "            except KeyboardInterrupt:\n",
        "                break\n",
        "        return\n",
        "\n",
        "    css_injection = \"\"\"\n",
        "    .think-panel { background-color: #1e293b; color: #cbd5e1; padding: 16px; border-radius: 8px; font-family: 'Courier New', monospace; }\n",
        "    .sandbox-panel { background-color: #0f172a; color: #34d399; padding: 16px; border-radius: 8px; border-left: 5px solid #10b981; }\n",
        "    \"\"\"\n",
        "    \n",
        "    def process_chat_stream_with_self_correction(user_message, chat_history):\n",
        "        active_prompt = (\n",
        "            \"System: You are an advanced AI assistant specialized in reasoning and self-correction.\\n\"\n",
        "            f\"User: {user_message}\\nAssistant: <think>\"\n",
        "        )\n",
        "        inputs = tokenizer([active_prompt], return_tensors=\"pt\").to(\"cuda\")\n",
        "        prompt_len = inputs[\"input_ids\"].shape[1]\n",
        "        \n",
        "        # Turn 1\n",
        "        with torch.no_grad():\n",
        "            out = model.generate(\n",
        "                **inputs,\n",
        "                max_new_tokens=1024,\n",
        "                pad_token_id=tokenizer.eos_token_id,\n",
        "                use_cache=True\n",
        "            )\n",
        "        turn1_text = tokenizer.decode(out[0][prompt_len:], skip_special_tokens=True)\n",
        "        \n",
        "        # Extract code & execute\n",
        "        dream_match = re.search(r\"<dream_code>(.*?)</dream_code>\", turn1_text, re.DOTALL)\n",
        "        dream_code = dream_match.group(1).strip() if dream_match else \"\"\n",
        "        \n",
        "        sandbox_evaluator = TeacherSandbox(search_adapter=search_adapter)\n",
        "        success, _, sandbox_terminal_logs = sandbox_evaluator.execute_safely(dream_code, \"assert True\", [])\n",
        "        \n",
        "        parts = turn1_text.split(\"</think>\")\n",
        "        think_text = parts[0].replace(\"<think>\", \"\").strip()\n",
        "        final_solution = parts[-1].strip() if len(parts) > 1 else active_prompt\n",
        "        \n",
        "        if not success:\n",
        "            # Turn 2: Self-correction trigger\n",
        "            turn2_prompt = (\n",
        "                f\"{active_prompt}{turn1_text}\\n\"\n",
        "                f\"<tool_response>{sandbox_terminal_logs}</tool_response>\\n\"\n",
        "                f\"<critique>\\n\"\n",
        "                f\"The code failed compiler execution. I will diagnose and correct.\\n\"\n",
        "                f\"</critique>\\n\"\n",
        "                f\"<conscious_reflection>\\n\"\n",
        "                f\"Correction strategy.\\n\"\n",
        "                f\"</conscious_reflection>\\n\"\n",
        "                f\"<think>\"\n",
        "            )\n",
        "            inputs2 = tokenizer([turn2_prompt], return_tensors=\"pt\").to(\"cuda\")\n",
        "            prompt_len2 = inputs2[\"input_ids\"].shape[1]\n",
        "            with torch.no_grad():\n",
        "                out2 = model.generate(\n",
        "                    **inputs2,\n",
        "                    max_new_tokens=1024,\n",
        "                    pad_token_id=tokenizer.eos_token_id,\n",
        "                    use_cache=True\n",
        "                )\n",
        "            turn2_text = tokenizer.decode(out2[0][prompt_len2:], skip_special_tokens=True)\n",
        "            \n",
        "            dream_match2 = re.search(r\"<dream_code>(.*?)</dream_code>\", turn2_text, re.DOTALL)\n",
        "            dream_code = dream_match2.group(1).strip() if dream_match2 else \"\"\n",
        "            success, _, sandbox_terminal_logs = sandbox_evaluator.execute_safely(dream_code, \"assert True\", [])\n",
        "            \n",
        "            parts2 = turn2_text.split(\"</think>\")\n",
        "            think_text += f\"\\n\\n--- [Turn 2 Self-Correction] ---\\n{parts2[0].replace('<think>', '').strip()}\"\n",
        "            final_solution = parts2[-1].strip() if len(parts2) > 1 else final_solution\n",
        "            \n",
        "        visual_html = (\n",
        "            f\"### \ud83d\udd2e Inside the Self-Correcting Mind-State:\\n\"\n",
        "            f\"<div class='think-panel'><pre>{think_text}</pre></div>\\n\\n\"\n",
        "            f\"### \ud83d\udda5\ufe0f Live Sandbox Terminal (Verification: {'Passed' if success else 'Failed'}):\\n\"\n",
        "            f\"<div class='sandbox-panel'><pre>Final Compiled Code:\\n{dream_code}\\n\\nConsole Log:\\n{sandbox_terminal_logs}</pre></div>\\n\\n\"\n",
        "            f\"### \ud83d\udcac Final Grounded Response:\\n\"\n",
        "            f\"{final_solution}\"\n",
        "        )\n",
        "        \n",
        "        chat_history.append((user_message, visual_html))\n",
        "        return \"\", chat_history\n",
        "\n",
        "    with gr.Blocks(theme=gr.themes.Soft(), css=css_injection) as agi_ui:\n",
        "        gr.Markdown(\"# \ud83d\udef8 Symmetrical Slerp-Merged Active Debugging Agent (LFM2.5-230M) v10\")\n",
        "        chatbot = gr.Chatbot(label=\"Active Cognition Streams\")\n",
        "        user_input = gr.Textbox(label=\"Query / Exploratory Directive\")\n",
        "        reset_btn = gr.Button(\"Clear Memory Buffer\")\n",
        "        \n",
        "        user_input.submit(process_chat_stream_with_self_correction, [user_input, chatbot], [user_input, chatbot])\n",
        "        reset_btn.click(lambda: None, None, chatbot, queue=False)\n",
        "\n",
        "    print(\"[INFO] Spinning up interactive web UI local server...\")\n",
        "    agi_ui.queue(default_concurrency_limit=1).launch(share=os.environ.get('GRADIO_SHARE', 'false').lower() in ('1', 'true', 'yes'), auth=((os.environ.get('GRADIO_AUTH_USER'), os.environ.get('GRADIO_AUTH_PASS')) if os.environ.get('GRADIO_AUTH_USER') and os.environ.get('GRADIO_AUTH_PASS') else None))\n",
        "\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    print(\"Initializing Kaggle training script with V3 AGI Pipeline on 50-sample slice of Small Dataset...\")\n",
        "    import os\n",
        "    os.environ[\"END_IDX\"] = \"50\"\n",
        "    \n",
        "    config = TrainingConfig()\n",
        "    config.max_seq_length = 1024\n",
        "    config.accumulation_steps = 4\n",
        "    config.save_checkpoint_dir = \"./checkpoints\"\n",
        "    \n",
        "    model, tokenizer, search_adapter = run_symmetrical_agi_pipeline(\n",
        "        \"/kaggle/input/minillm-small-dataset/dataset_small.json\", \n",
        "        config=config\n",
        "    )\n",
        "    print(\"Training and GGUF conversions completed successfully.\")\n"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 2
}